/**
 * TODO: Remove with first stable release
 * UNTIL THIS PROJECT REACHED A FINAL STATE IT IS CONSIDERED SAFE
 * TO UPDATE, GROUP AND RE-ORDER NUMBERS IN A CONSECUTIVE ORDER!
 */
export enum ErrorCode {
    INTERNAL_ERROR = -1,

    INVALID_TOKEN = 1,
    INVALID_PAYLOAD = 2,
    INVALID_PASSWORD = 3,
    INVALID_MFA_CODE = 4,
    INVALID_BACKUP_CODE = 5,

    DUPLICATE_USERNAME = 6,
    DUPLICATE_EMAIL = 7,

    LOCKED_USERNAME = 8,
    LOCKED_ACCOUNT = 9,
    LOCKED_PASSWORD = 10,

    MISSING_TOKEN = 11,
    USER_NOT_FOUND = 12,
    NOT_ADMIN = 13,
    NOT_SET_UP = 14,
    EMAIL_FAILED_TO_DELIVER = 15,
    MFA_INVALID_ACTION = 16
}
